//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olimpiadas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificaciones
    {
        public int Id { get; set; }
        public int dorsal { get; set; }
        public int idPrueba { get; set; }
        public string fecha { get; set; }
        public int posicion { get; set; }
    
        public virtual Deportista Deportista { get; set; }
        public virtual Prueba Prueba { get; set; }
    }
}
