//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olimpiadas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deportista
    {
        public Deportista()
        {
            this.Calificaciones = new HashSet<Calificaciones>();
        }
    
        public int dorsal { get; set; }
        public string nombre { get; set; }
        public int edad { get; set; }
        public int calificacion { get; set; }
        public string email { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public string ISO { get; set; }
    
        public virtual Pais Pais { get; set; }
        public virtual ICollection<Calificaciones> Calificaciones { get; set; }
    }
}
