//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olimpiadas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OlimpiadasContainer : DbContext
    {
        public OlimpiadasContainer()
            : base("name=OlimpiadasContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Pais> Paises { get; set; }
        public DbSet<Deportista> Deportistas { get; set; }
        public DbSet<Prueba> Pruebas { get; set; }
        public DbSet<Calificaciones> Calificaciones { get; set; }
    }
}
