//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olimpiadas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pais
    {
        public Pais()
        {
            this.Deportistas = new HashSet<Deportista>();
        }
    
        public string ISO { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<Deportista> Deportistas { get; set; }
    }
}
